name: Deploy Scala API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: coursier/setup-action@v1

      - name: Install dependencies
        run: sbt update

      - name: Run tests
        run: sbt test

      - name: Package the application
        run: sbt assembly

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy Scala API"
          git push origin main
